# Generated by Django 4.0.4 on 2022-05-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_user_city_user_phonenumber_user_street_user_zgoda1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=15, verbose_name='Username'),
        ),
    ]
