# Generated by Django 4.0.4 on 2022-05-13 15:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='Nazwa')),
                ('pictures', models.ImageField(blank=True, upload_to='static/images/building', verbose_name='Zdjęcia')),
                ('regulamin', models.FileField(blank=True, upload_to='static/regulamin', verbose_name='Regulamin')),
                ('info', models.TextField(blank=True, default='', verbose_name='Informacje')),
                ('building_adres', models.TextField(default='', verbose_name='Adres')),
                ('firm_adres', models.TextField(blank=True, default='', verbose_name='Adres')),
                ('telefon1', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Telefon')),
                ('telefon2', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Telefon')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=3, verbose_name='Segment')),
                ('pictures', models.ImageField(blank=True, upload_to='static/images/segments', verbose_name='Zdjęcia')),
                ('description', models.TextField(blank=True, default='', verbose_name='Opis')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.building')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=15, verbose_name='Imię')),
                ('last_name', models.CharField(default='', max_length=15, verbose_name='Nazwisko')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='E-mail')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Telefon')),
                ('street', models.CharField(default='', max_length=50, verbose_name='Adres')),
                ('zip_code', models.CharField(default='', max_length=6, verbose_name='Kod pocztowy')),
                ('city', models.CharField(default='', max_length=20, verbose_name='Miejscowość')),
                ('adults', models.SmallIntegerField(default=1, verbose_name='Liczba dorosłych')),
                ('childs', models.SmallIntegerField(default=0, verbose_name='Liczba dzieci')),
                ('questions', models.TextField(blank=True, default='', verbose_name='Zapytania')),
                ('zgoda1', models.BooleanField(default=False, verbose_name='Wyrażam zgodę na otrymanie na podany przeze mnie w formularzu adres e-mail oraz numer telefonu informacji w zakresie związanym ze zlożona rezerwacje przeze mnie')),
                ('zgoda2', models.BooleanField(default=False, verbose_name='Zapoznałem się z Regulaminem i akceptuję jego postanowienia')),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Oczekuję'), ('confirmed', 'Potwirdzona'), ('ended', 'Zakonczona')], default=('pending', 'Oczekuję'), max_length=15, verbose_name='Status')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
        ),
    ]
