# Generated by Django 4.0.4 on 2022-05-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_building_room_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
        ),
    ]
