# Generated by Django 4.0.4 on 2022-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.SmallIntegerField(default=5, verbose_name='Ilość miejsc'),
        ),
    ]
